### ISSUE TITLE
Error in tensorflow-java/LabelImage.java

### ISSUE THREAD

**Issue by Harish120896** [loretoparisi/tensorflow-java#2]
When i try to run my model already trained model with your code it says 
"No Operation named [output] in the Graph"
It happens in the line as follows : 
s.runner().feed("input", image).fetch("output").run().get(0).expect(Float.class)) { // happens in this line..
What has to be done. Any  help is appreciated.

**Comment by loretoparisi** [comment]
@Harish120896 if you try the example provided and TF 1.6.0, it works? Just to be sure that your setup it's ok. Let me know, please follows this instructions: https://github.com/loretoparisi/tensorflow-java#real-world-inception-example

**Comment by Harish120896** [comment]
No. Error was actually with the string that we pass on to the feed and fetch function. It has to match with our retrained pb file. That was the error. Sorted out the issue.Works fine now.

**Comment by loretoparisi** [comment]
@Harish120896 Glad you have found a fix for that!
